//find the difference
//You are given two strings s and t.String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.
//s =abcd  ; t=abcde
//we are using here multiple approaches. 

//without extra space --> XOR method
class Solution {
    public char findTheDifference(String s, String t) {
        char ans = 0 ;
        for(char c : s.toCharArray()){
            ans^=c ;
        }
        for(char c : t.toCharArray()){
            ans^=c ;
        }
        return ans ;
    }
}
  //approach  2 : frequency array
  class Solution {
    public char findTheDifference(String s, String t) {
      int[] arr = new int[26];
      for(char c : t.toCharArray(){
        freq[c-'a']++;
      }
      for(char c : s.toCharArray(){
        freq[c-'a']--;
        if(freq[c - 'a'] <0){
          return c ;
        }
      }
      return ' ' ;
    }
}
//approach 3 : ASCII difference
class Solution {
    public char findTheDifference(String s, String t) {
        int sum = 0;

        for (char c : t.toCharArray()) sum += c;
        for (char c : s.toCharArray()) sum -= c;

        return (char) sum;
    }
}


